spring:
  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkK
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fitmate?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: fitmate
    password: fitmate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379
  program:
    max-active-program-limit: 3
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
rabbitmq:
  notifications:
    topic-exchange:
      name: notifications-exchange
    queue:
      name: notifications
    routing-key:
      name: notifications.#
      daily-9am:
        name: notifications.daily.9am